name: Candlestick Frontend Pipeline

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  deploy_image_job:
        name: Deploy Docker Image
        #if: github.ref == 'refs/head/main'
        #needs: build_image_job
        outputs:
          APP_INGRESS_URL: ${{ steps.set-ingress-host-id.outputs.APP_INGRESS_HOST}}
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Install Kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.33.6'

            - name: Set Kubeconfig
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}
                
            - name: Fetch Kubernetes CLuster Details
              run: |
                  kubectl version
                  echo ............................
                  kubectl get nodes

            - name: Replace Token in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS}}
                IMAGE: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Check Files
              run: |
                  cat kubernetes/development/*.yaml

            - name: Deploy to Dev Env
              run: |
                  kubectl apply -f kubernetes/development

            - name: Set App Ingress Host URL
              id: set-ingress-host-id
              run: |
                  echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o json | jq -r '.items[] | .spec.rules[] | .host')" >> "$GITHUB_OUTPUT"
                  #echo $APP_INGRESS_HOST
    integration_test_job:
        name: Dev Integration Testing
        #if: github.ref == 'refs/head/main'
        needs: deploy_image_job
        runs-on: self-hosted
        steps:
            - name: Test URL Output using cURL
              env:
                URL: ${{ needs.deploy_image_job.outputs.APP_INGRESS_URL }}
              run: |
                  echo $URL
                  echo "................................"
                  curl http://$URL
